version: "3.1"

services:
  projeto_etb:
    image: postgres:14.6-alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projeto_etb
    ports:
      - "5432:5432"